### ISSUE TITLE
Add friend system

### ISSUE THREAD

**Issue by minglangdu** [GoodPositiveKid/Chat-website#5]
Create a friend system.
# Tasks
- [x] Create a new table for friends 
- [x] Allow friends to be added
- [x] #9
- [x] Allow friends to be seen
- [x] Allow friends to be removed
